version: '3'

services:
  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "JIRARUSH_DB_USER=${JIRARUSH_DB_USER}"
      - "JIRARUSH_DB_PASSWORD=${JIRARUSH_DB_PASSWORD}"
      - "JIRARUSH_GITHUB_SECRET=${JIRARUSH_GITHUB_SECRET}"
      - "JIRARUSH_GITLAB_SECRET=${JIRARUSH_GITLAB_SECRET}"
      - "JIRARUSH_GOOGLE_SECRET=${JIRARUSH_GOOGLE_SECRET}"
      - "JIRARUSH_MAIL_PASSWORD=${JIRARUSH_MAIL_PASSWORD}"
    volumes:
      - ./resources/mails:/resources/mails
      - ./resources/view:/resources/view
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ${JIRARUSH_DB_USER}
      POSTGRES_PASSWORD: ${JIRARUSH_DB_PASSWORD}
      POSTGRES_DB: jira
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./resources:/opt/jirarush/resources
    depends_on:
      - app
